django_basico/tribu/echos/urls.py
from django.urls import path

from . import views

app_name = 'echos'  # This is your app name in the URL

urlpatterns = [
    path('', views.echos_list, name='echos-list'),
    path('add/', views.add_echo, name='echos-add'),
    path('<int:id>/', views.echo_detail, name='echo-details'),
    path('<int:id>/edit/', views.edit_echo, name='echo-edit'),
    path('<int:id>/delete/', views.delete_echo, name='echo-delete'),
    path('<int:id>/waves/', views.echo_all_waves, name='echo-waves'),
    path('<int:id>/waves/add/', views.add_wave_to_echo, name='echo-add-wave'),
]

django_basico/tribu/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from accounts import views

urlpatterns = [
    path('', lambda _: redirect('echos/')),
    path('admin/', admin.site.urls),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('echos/', include('echos.urls')),
    path('waves/', include('waves.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_basico/tribu/users/urls.py
from django.urls import path

from . import views

app_name = 'users'  # This is your app name in the URL

urlpatterns = [
    path('', views.user_list, name='user-list'),
    path('@me/', views.self_profile, name='self-profile'),
    path('<str:username>/', views.user_details, name='user-profile'),
    path('<str:username>/echos/', views.user_echo_details, name='user-echos'),
    path('<str:username>/edit/', views.edit_user, name='user-edit'),
]

django_basico/tribu/users/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.png')

    def __str__(self):
        return self.bio

    def get_absolute_url(self):
        return reverse('users:user-profile', kwargs={'id': self.id})

django_basico/tribu/users/forms.py
from django import forms

from .models import Profile


class User_edit_form(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'avatar')
        labels = {
            'bio': 'Bio',
            'avatar': 'Avatar',
        }
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control mb-3'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control mb-3'}),
        }

django_basico/tribu/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render

from echos.models import Echo

from .forms import User_edit_form

# Create your views here.


@login_required
def user_list(request):
    users = get_user_model().objects.all()
    return render(request, 'user_list.html', {'users': users})


@login_required
def user_details(request, username):
    user = get_user_model().objects.get(username=username)
    return render(
        request,
        'user_details.html',
        {
            'other_user': user,
            'echos': Echo.objects.filter(user=user)[:5],
        },
    )


@login_required
def user_echo_details(request, username):
    user = get_user_model().objects.get(username=username)

    return render(
        request,
        'user_details.html',
        {
            'other_user': user,
            'echos': Echo.objects.filter(user=user),
        },
    )


@login_required
def self_profile(request):
    return redirect('users:user-profile', request.user.username)


@login_required
def edit_user(request, username):
    user = get_user_model().objects.get(username=username)
    profile = user.profile

    if request.user != user:
        return HttpResponseForbidden()

    if request.method == 'POST':
        user_form = User_edit_form(request.POST, request.FILES, instance=profile)

        if user_form.is_valid():
            profile = user_form.save()
            return redirect('users:user-profile', username=user.username)
    else:
        user_form = User_edit_form(instance=profile)

    return render(request, 'user_edit_form.html', {'form': user_form})

django_basico/tribu/users/templates/user_details.html
{% extends "Base.html" %}

{% block title %}
~User Details~
{% endblock title %}

{% block body %}
  <div class="conatiner">
    <div class="card">
      <div class="card-header d-flex align-items-center g-4">
        <img class="img-fluid" src="{{other_user.profile.avatar.url}}" alt="Avatar" width="100px">
        <h1 class="card-title ms-4" >{{ other_user.username }}</h1>
      </div>
      <div class="card-body">
        <p class="card-text" >Bio: {{ other_user.profile.bio }}</p>
        <p>Registered: {{ other_user.created_at|date:"F d, Y" }}</p>
        <ul class="list-group">
          {% for echo in echos %}
            <li class="list-group-item">
              <a href="{% url 'echos:echo-details' echo.id %}" class="list-group-item list-group-item-action list-group-item-info" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ echo.user.username }}</h5>
                  <small>{{ echo.created_at|date:"F d, Y" }}</small>
                </div>
                <p class="mb-1">{{ echo.content|truncatewords:20 }}</p>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% if other_user.echos.count > 5 and echos.count < 6 %}
        <div class="card-footer">
          <a href="{% url 'users:user-echos' other_user.username %}">See all</a>
        </div>
      {% endif %}
      {% if user == other_user %}
        <a href="{% url 'users:user-edit' user.username %}" class="btn btn-outline-success">Edit</a>
      {% endif %}
    </div>

    
  </div>
{% endblock body %}

django_basico/tribu/users/templates/user_edit_form.html
{% extends "Base.html" %}

{% block title %}
  Add {{ object_name }} 
{% endblock title %}

{% block body %}
    <form method="post" novalidate class="mt-9" enctype="multipart/form-data">
      <br>
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="enviar" class="btn btn-info">
    </form>
{% endblock body %}

django_basico/tribu/users/templates/user_list.html
{% extends "Base.html" %}

{% block title %}
~User List~
{% endblock title %}

{% block body %}
<div class="row gap-4 container-fluid">
  <div class="list-group">
    {% for user in users %}
      <a href="{% url 'users:user-profile' user.username %}" class="list-group-item list-group-item-action list-group-item-success" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ user.username }}</h5>
          <small>Registered {{ user.created_at|timesince }} Ago</small>
        </div>
        <p class="mb-1">{{ user.profile.bio|truncatewords:10 }}</p>
      </a>
    {% endfor %}
  </div>
</div> 
{% endblock body %}