django_basico/ultra-task/task/urls.py
from django.urls import path

from . import views

app_name = 'task'  # This is your app name in the URL

urlpatterns = [
    path('', views.home, name='home'),
    path('task/add/', views.addTask, name='add_task'),
    path('task/done/', views.done, name='done'),
    path('task/undone/', views.undone, name='undone'),
    path('task/<task_slug>/', views.task_detail, name='task_detail'),
]

django_basico/ultra-task/task/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    due_date = models.DateField()
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

django_basico/ultra-task/task/forms.py
from django import forms

from .models import Task


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'completed', 'due_date')

django_basico/ultra-task/task/views.py
from datetime import date

from django.shortcuts import redirect, render
from django.utils.text import slugify

from .forms import AddTaskForm
from .models import Task


def home(request):
    all_tasks = Task.objects.all()

    finished = [task for task in all_tasks if task.completed]
    not_finished = [task for task in all_tasks if not task.completed]

    return render(request, 'task/home.html', {'completed': finished, 'uncompleted': not_finished})


def task_detail(request, task_slug):
    task = Task.objects.get(slug=task_slug)
    time_left = (task.due_date - date.today()).days
    return render(request, 'task/task_detail.html', {'task': task, 'time_left': time_left})


def done(request):
    all_tasks = Task.objects.all()
    finished = [task for task in all_tasks if task.completed]
    status = 'Done'
    return render(request, 'task/task_list.html', {'tasks': finished, 'status': status})


def undone(request):
    all_tasks = Task.objects.all()
    not_finished = [task for task in all_tasks if not task.completed]
    status = 'Done'
    return render(request, 'task/task_list.html', {'tasks': not_finished, 'status': status})


def addTask(request):
    if request.method == 'POST':
        addTaskForm = AddTaskForm(request.POST)
        if addTaskForm.is_valid():
            title = addTaskForm.cleaned_data['title']
            description = addTaskForm.cleaned_data['description']
            completed = addTaskForm.cleaned_data['completed']
            due_date = addTaskForm.cleaned_data['due_date']

            task = Task(
                title=title,
                description=description,
                completed=completed,
                due_date=due_date,
                slug=slugify(title),
            )

            task.save()
            return redirect('task:home')
    else:
        addTaskForm = AddTaskForm()
    return render(request, 'task/addTask.html', {'addTaskForm': addTaskForm})

django_basico/ultra-task/task/templates/task/addTask.html
{% extends "task/base.html" %}

{% block title %}
  Add Task 
{% endblock title %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ addTaskForm }}
    <input type="submit" value="enviar" class="btn">
  </form>
{% endblock body %}

django_basico/ultra-task/task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} ToDo {% endblock title %}</title>
  <link rel="stylesheet" href="{% static 'task/styles.css' %}">
</head>

<body>
  {% block body %}

  {% endblock body %}
</body>

</html>

django_basico/ultra-task/task/templates/task/home.html
{% extends "task/base.html" %}

{% block title %}
    Home
{% endblock title %}

{% block body %}
    <h1 class="text">To Do:</h1>
    
    <div class="container">
        <div class="innerContainer">
            <h2 class="text"><a href="{% url 'task:done' %}" class="text">Not Done ({{ uncompleted|length }})</a></h2>
            
            <div class="scrollContainer">
                {% for task in uncompleted %}
                    <div class="taskCard">
                        <div class="taskHeader">
                            <div class="text taskTittle">{{ task.title|truncatewords:5 }}</div>
                            <div class="text headerDate">Due: {{ task.due_date }}</div>
                        </div>
        
                        <div class="taskBody">
                            <p class="text">{{ task.description }}</p>
                            <a href="{% url 'task:task_detail' task.slug %}">View Details</a>
                            <div class="dateContainer">
                                <div class="text">Created At: {{ task.created_at }}</div>
                                <div class="text">Last Update: {{ task.updated_at }}</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        
        <div class="innerContainer">
            <h2 class="text"><a href="{% url 'task:done' %}" class="text">Done ({{ completed|length }})</a></h2>
            <div class="scrollContainer">
            {% for task in completed %}
                <div class="taskCard">
                    <div class="taskHeader">
                        <div class="taskTittle doneText">{{ task.title|truncatewords:5 }}</div>
                        <div class="headerDate">Due: {{ task.due_date }}</div>
                    </div>
        
                    <div class="taskBody">
                        <p class="doneText">{{ task.description }}</p>
                        <a href="{% url 'task:task_detail' task.slug %}">View Details</a>
                        <div class="dateContainer">
                            <div>{{ task.created_at }}</div>
                            <div>{{ task.updated_at }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>

    <div class="addTaskContainer">
        <a href="{% url 'task:add_task' %}">Add New Task</a>
    </div>
{% endblock body %}

django_basico/ultra-task/task/templates/task/task_detail.html
{% extends "task/base.html" %}

{% block title %}
  Details 
{% endblock title %}

{% block body %}
<div class="taskCard">
    <div class="taskHeader">
        <div class="text taskTittle">{{ task.title }}</div>
        <div class="text">
            Status: 
            {% if task.completed %}
                Done    
            {% else %}
                Not Done
            {% endif %}
        </div>
        <div class="text headerDate">Due: {{ task.due_date }}</div>
    </div>

    <div class="taskBody">
        <p class="text">{{ task.description }}</p>
        <div class="text">{{ time_left }} Days Until Due</div>
        <a href="{% url 'task:home' %}">Back to home</a>
        <div class="dateContainer">
            <div class="text">Created At: {{ task.created_at }}</div>
            <div class="text">Last Update: {{ task.updated_at }}</div>
        </div>
    </div>
</div>
{% endblock body %}

django_basico/ultra-task/task/templates/task/task_list.html
{% extends "task/base.html" %}

{% block title %}
  Details 
{% endblock title %}

{% block body %}
    <h1 class="text">{{ tasks|length }} task{{ tasks|length|pluralize }} {{ status }}</h1>
    {% for task in tasks %}
        <div class="taskCard">
            <div class="taskHeader">
                <div class="text taskTittle">{{ task.title|truncatewords:5 }}</div>
                <div class="text headerDate">Due: {{ task.due_date }}</div>
            </div>

            <div class="taskBody">
                <p class="text">{{ task.description }}</p>
                <a href="{% url 'task:task_detail' task.slug %}">View Details</a>
                <div class="dateContainer">
                    <div class="text">Created At: {{ task.created_at }}</div>
                    <div class="text">Last Update: {{ task.updated_at }}</div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock body %}