django_basico/supertodo/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'  # This is your app name in the URL

urlpatterns = [
    path('', views.task_list, name='task-list'),
    path('add/', views.addTask, name='add-task'),
    path('done/', views.done, name='done'),
    path('pending/', views.pending, name='pending'),
    path('task/<task_slug>/', views.task_detail, name='task-detail'),
    path('task/<task_slug>/toggle/', views.toggle, name='task-toggle'),
    path('task/<task_slug>/edit/', views.edit, name='task-edit'),
    path('task/<task_slug>/delete/', views.delete, name='task-delete'),
]

django_basico/supertodo/tasks/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    done = models.BooleanField(default=False)
    complete_before = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_basico/supertodo/tasks/forms.py
from django import forms

from .models import Task


class Complete_before(forms.TextInput):
    input_type = 'datetime-local'


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'complete_before')
        lables = {
            'name': 'Task Title',
            'description': 'Task Description',
            'complete_before': 'Complete Before (days)',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'description': forms.Textarea(attrs={'class': 'form-control mb-3'}),
            'complete_before': Complete_before(attrs={'class': 'form-control mb-3'}),
        }


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'complete_before', 'done')
        lables = {
            'name': 'Task name',
            'description': 'Task Description',
            'complete_before': 'Complete Before (days)',
            'done': 'Task Completed',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-3'}),
            'description': forms.Textarea(attrs={'class': 'form-control mb-3'}),
            'complete_before': Complete_before(attrs={'class': 'form-control mb-3'}),
            'done': forms.CheckboxInput(attrs={'class': ' mb-3'}),
        }

django_basico/supertodo/tasks/views.py
from datetime import date

from django.shortcuts import redirect, render
from django.utils.text import slugify

from .forms import AddTaskForm, EditTaskForm
from .models import Task


def task_list(request):
    all_tasks = Task.objects.all()
    status = 'All Tasks'

    return render(request, 'tasks/task_list.html', {'tasks': all_tasks})


def done(request):
    all_tasks = Task.objects.all()
    done = list(filter(lambda task: task.done, all_tasks))
    status = 'Done'
    return render(request, 'tasks/task_list.html', {'tasks': done, 'status': status})


def pending(request):
    all_tasks = Task.objects.all()
    pending = list(filter(lambda task: not task.done, all_tasks))
    status = 'Pending'
    return render(request, 'tasks/task_list.html', {'tasks': pending, 'status': status})


def task_detail(request, task_slug):
    task = Task.objects.get(slug=task_slug)
    if task.complete_before:
        time_left = (task.complete_before - date.today()).days
    else:
        time_left = -1
    return render(request, 'tasks/task_detail.html', {'task': task, 'time_left': time_left})


def addTask(request):
    if request.method == 'POST':
        addTaskForm = AddTaskForm(request.POST)
        if addTaskForm.is_valid():
            name = addTaskForm.cleaned_data['name']
            description = addTaskForm.cleaned_data['description']
            complete_before = addTaskForm.cleaned_data['complete_before']

            task = Task(
                name=name,
                description=description,
                done=False,
                complete_before=complete_before,
                slug=slugify(name),
            )

            task.save()
            return redirect('tasks:task-list')
    else:
        addTaskForm = AddTaskForm()
    return render(request, 'tasks/taskForms.html', {'taskForm': addTaskForm})


def toggle(request, task_slug):
    task = Task.objects.get(slug=task_slug)
    task.done = not task.done
    task.save()
    return redirect('tasks:task-list')


def delete(request, task_slug):
    Task.objects.filter(slug=task_slug).delete()
    return redirect('tasks:task-list')


def edit(request, task_slug):
    task = Task.objects.get(slug=task_slug)

    if request.method == 'POST':
        editTaskForm = EditTaskForm(request.POST)
        if editTaskForm.is_valid():
            task.name = editTaskForm.cleaned_data['name']
            task.slug = slugify(task.name)
            task.description = editTaskForm.cleaned_data['description']
            task.done = editTaskForm.cleaned_data['done']
            task.complete_before = editTaskForm.cleaned_data['complete_before']

            task.save()
            return redirect('tasks:task-list')
    else:
        editTaskForm = EditTaskForm(instance=task)

    return render(request, 'tasks/taskForms.html', {'taskForm': editTaskForm})

django_basico/supertodo/tasks/templates/tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} ToDo {% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand text-warning" href="{% url 'tasks:task-list' %}">Super To Do</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item bottom-border">
            <a class="nav-link text-warning-emphasis" href={% url 'tasks:done' %}>Done</a>
          </li>
          <li class="nav-item bottom-border">
            <a class="nav-link text-warning-emphasis" href={% url 'tasks:pending' %}>Pending</a>
          </li>
          <li class="nav-item bottom-border">
            <a class="nav-link text-warning-emphasis" href={% url 'tasks:add-task' %}>Add Task</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block body %}

    {% endblock body %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>

</html>

django_basico/supertodo/tasks/templates/tasks/taskForms.html
{% extends "tasks/base.html" %}

{% block title %}
  Add Task 
{% endblock title %}

{% block body %}
  <form method="post" novalidate>
    <br>
    {% csrf_token %}
    {{ taskForm }}
    <input type="submit" value="enviar" class="btn btn-info">
  </form>
{% endblock body %}

django_basico/supertodo/tasks/templates/tasks/task_detail.html
{% extends "tasks/base.html" %}

{% block title %}
  Details 
{% endblock title %}

{% block body %}

<div class="card" style="margin-top: 10px">
    <div class="card-header">
        <h5 class="card-title">
            {{ task.name }}
        </h5>
    </div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Status: 
            {% if task.done %}
                Done    
            {% else %}
                Not Done
            {% endif %}
        </li>
        <li class="list-group-item card-subtitle mb-2 text-body-secondary">
            Due: {{ task.complete_before }}
        </li>
    </ul>
    
    <div class="card-body">
        <h6 class="">Due: {{ task.due_date }}</h6>
        <p class="card-text">{{ task.description }}</p>
    </div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <a href="{% url 'tasks:task-list' %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Back to home</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'tasks:task-edit' task.slug %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Edit Task</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'tasks:task-delete' task.slug %}" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Delete Task</a>
        </li>
        <li class="list-group-item">
            <a href="{% url 'tasks:task-toggle' task.slug %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                Toggle Task
            </a>
        </li>
    </ul>

    <div class="card-footer">
        <h6 class="card-subtitle mb-2 text-body-secondary">
            Created At: {{ task.created_at }}
        </h6>
        <h6 class="card-subtitle mb-2 text-body-secondary">
            Last Update: {{ task.updated_at }}
        </h6>
    </div>            
</div>
{% endblock body %}

django_basico/supertodo/tasks/templates/tasks/task_list.html
{% extends "tasks/base.html" %}

{% block title %}
  ~Home Page~ 
{% endblock title %}

{% block body %}
    <h1 class="text mt-4">
        {{ tasks|length }} Task{{ tasks|length|pluralize }} 
        {% if status %}
            {{ status }}
        {% endif %}
    </h1>

    <div class="container-fluid d-flex flex-nowrap align-content-center mt-3">
        <div class="row gap-4 container-fluid">
            {% for task in tasks %}
                <div class="card col-3 mb-4">
                    <div class="card-header">
                        {% if task.done %}
                            <h5 class="card-title text-decoration-line-through">
                                {{ task.name|truncatewords:4 }}
                            </h5>
                        {% else %}
                            <h5 class="card-title">
                                {{ task.name|truncatewords:4 }}
                            </h5>
                        {% endif %}
                    </div>
                    
                    <div class="card-body">
                        {% if task.done %}
                            <h6 class="card-subtitle mb-2 text-body-secondary">Due: {{ task.complete_before|default_if_none:"Not Specified" }}</h6>
                            {% if task.description %}
                                <p class="text-decoration-line-through card-text" style="height: 35%">{{ task.description|truncatewords:15 }}</p>
                            {% else %}
                                <p class="card-text" style="height: 35%">No Description Given</p>
                            {% endif %}
                            
                        {% else %}
                        <h6 class="card-subtitle mb-2 text-body-secondary">Due: {{ task.complete_before|default_if_none:"Not Specified" }}</h6>
                            {% if task.description %}
                                <p class="card-text" style="height: 35%">{{ task.description|truncatewords:15 }}</p>
                            {% else %}
                                <p class="card-text" style="height: 35%">No Description Given</p>
                            {% endif %}
                        {% endif %}
                        
                    </div>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'tasks:task-detail' task.slug %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover card-link">View Details</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'tasks:task-edit' task.slug %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Edit Task</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'tasks:task-delete' task.slug %}" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Delete Task</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'tasks:task-toggle' task.slug %}" class="link-info link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Toggle Task</a>
                        </li>
                    </ul>

                    <div class="card-footer" style="height: 22%">
                        <h6 class="card-subtitle mb-2 text-body-secondary">
                            Created At: {{ task.created_at }}
                        </h6>
                        <h6 class="card-subtitle mb-2 text-body-secondary">
                            Last Update: {{ task.updated_at }}
                        </h6>
                    </div>            
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock body %}