django_basico/tribu/echos/urls.py
from django.urls import path

from . import views

app_name = 'echos'  # This is your app name in the URL

urlpatterns = [
    path('', views.echos_list, name='echos-list'),
    path('add/', views.add_echo, name='echos-add'),
    path('<int:id>/', views.echo_detail, name='echo-details'),
    path('<int:id>/edit/', views.edit_echo, name='echo-edit'),
    path('<int:id>/delete/', views.delete_echo, name='echo-delete'),
    path('<int:id>/waves/', views.echo_all_waves, name='echo-waves'),
    path('<int:id>/waves/add/', views.add_wave_to_echo, name='echo-add-wave'),
]

django_basico/tribu/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from accounts import views

urlpatterns = [
    path('', lambda _: redirect('echos/')),
    path('admin/', admin.site.urls),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('echos/', include('echos.urls')),
    path('waves/', include('waves.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_basico/tribu/waves/urls.py
from django.urls import path

from . import views

app_name = 'waves'  # This is your app name in the URL

urlpatterns = [
    path('<int:id>/edit/', views.edit_wave, name='wave-edit'),
    path('<int:id>/delete/', views.delete_wave, name='wave-delete'),
]

django_basico/tribu/echos/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.


class Echo(models.Model):
    content = models.TextField(null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='echos',
    )

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('echos:echo-details', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_at']

django_basico/tribu/echos/forms.py
from django import forms

from .models import Echo


class AddEchoForm(forms.ModelForm):
    class Meta:
        model = Echo
        fields = ('content',)
        lables = {
            'content': 'Echo content',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control mb-3'}),
        }

django_basico/tribu/echos/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render

from waves.forms import WaveAddForm
from waves.models import Wave

from .forms import AddEchoForm

# Create your views here.
from .models import Echo


@login_required
def echos_list(request):
    echos = Echo.objects.all()
    return render(request, 'EchosList.html', {'echos': echos})


@login_required
def add_echo(request):
    if request.method == 'POST':
        addEchoForm = AddEchoForm(request.POST)
        if addEchoForm.is_valid():
            content = addEchoForm.cleaned_data['content']

            echo = Echo(
                content=content,
                user=request.user,
            )

            echo.save()
            return redirect('echos:echos-list')
    else:
        addEchoForm = AddEchoForm()
        return render(request, 'Forms.html', {'form': addEchoForm, 'object_name': 'Echo'})


@login_required
def echo_detail(request, id):
    echo = Echo.objects.get(id=id)

    return render(
        request,
        'EchoDetail.html',
        {
            'echo': echo,
            'waves': echo.waves.all()[:5],
            'form': WaveAddForm(),
        },
    )


@login_required
def echo_all_waves(request, id):
    echo = Echo.objects.get(id=id)

    return render(
        request,
        'EchoDetail.html',
        {
            'echo': echo,
            'waves': echo.waves.all(),
            'form': WaveAddForm(),
        },
    )


@login_required
def add_wave_to_echo(request, id):
    echo = Echo.objects.get(id=id)

    wave = Wave(
        echo=echo,
        user=request.user,
        content=request.POST.get('content'),
    )
    wave.save()

    return render(request, 'EchoDetail.html', {'echo': echo, 'form': WaveAddForm()})


@login_required
def edit_echo(request, id):
    echo = Echo.objects.get(id=id)
    if request.user != echo.user:
        return HttpResponseForbidden()

    if request.method == 'POST':
        editEchoForm = AddEchoForm(request.POST, instance=echo)
        if editEchoForm.is_valid():
            content = editEchoForm.cleaned_data['content']

            echo.content = content
            echo.save()
            return redirect('echos:echos-list')
    else:
        editEchoForm = AddEchoForm(instance=echo)
        return render(request, 'Forms.html', {'form': editEchoForm, 'object_name': 'Echo'})


@login_required
def delete_echo(request, id):
    echo = Echo.objects.get(id=id)
    if request.user != echo.user:
        return HttpResponseForbidden()

    echo.delete()
    return redirect('echos:echos-list')


@login_required
def echoWaves(request, id):
    echo = Echo.objects.get(id=id)
    return render(request, 'EchoDetail.html', {'echo': echo})

django_basico/tribu/echos/templates/EchoDetail.html
{% extends "Base.html" %}

{% block title %}
~Echo Details~
{% endblock title %}

{% block body %}
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">By: {{ echo.user.username }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">Posted At: {{ echo.created_at|date:"F d, Y" }}</h6>
        <p class="card-text"> {{ echo.content }}</p>
        {% if echo.user == user %}
          <a href="{% url 'echos:echo-edit' echo.id %}" class="card-link link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Edit Echo</a>
          <a href="{% url 'echos:echo-delete' echo.id %}" class="card-link link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Delete Echo</a>
        {% endif %}
      </div>

      <div class="card-footer">
        <form method="post" novalidate action="{% url "echos:echo-add-wave" echo.id %}">
          {% csrf_token %}
          {{ form }}
          <input type="submit" value="enviar" class="btn btn-info">
        </form>
      </div>

      <ul class="list-group">
        {% for w in waves %}
          <div class="card-body">
            <h5 class="card-title">Answered By: {{ w.user.username }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ w.created_at | timesince}} ago</h6>
            <p class="card-text"> {{ w.content }}</p>
            {% if w.user == user %}
              <a href="{% url 'waves:wave-edit' w.pk %}" class="card-link link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Edit Wave</a>
              <a href="{% url 'waves:wave-delete' w.pk %}" class="card-link link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Delete Wave</a>
            {% endif %}
          </div>
        {% endfor %}
      </ul>

      {% if echo.waves.count > 5 and waves.count < 6 %}
        <a class="btn btn-outline-info m-1" href="{% url "echos:echo-waves" echo.pk %}">
          See All The Waves
        </a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock body %}

django_basico/tribu/echos/templates/EchosList.html
{% extends "Base.html" %}

{% block title %}
  ~Home Page~ 
{% endblock title %}

{% block body %}
<div class="row gap-4 container-fluid">
  <div class="list-group">
    {% for e in echos %}
      <a href="{% url 'echos:echo-details' e.id %}" class="list-group-item list-group-item-action list-group-item-success" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ e.user.username }}</h5>
          <small>Created At: {{ e.created_at|date:"F d, Y" }}</small>
        </div>
        <p class="mb-1">{{ e.content|truncatewords:20 }}</p>
      </a>
    {% endfor %}
  </div>
</div> 
{% endblock %}